fix: skip incorrect action_date instead of failing c7n
Since 'action_date' is parsed in try/except block, there is an issue
if parsing of 'action_date' fails, because Python 'action_date' variable
is used later

Error example:

UnboundLocalError: local variable 'action_date' referenced before assignment