modified the type signature from Callable[[dict, str], None] to  Callable[[{}, str], None] see if this cures a runtime error on Python 3.8
def expect(self, calls: list[str], on_error: Callable[[dict, str], None] = _default_on_err):
  TypeError: 'type' object is not subscriptable