Fixed the snapshot example as it was erroring out
The example for snapshots in ec2.py was erroring out with the following error:
```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<string>", line 8, column 15:
         copy-tags:
```
once I changed - snapshot to - type: snapshot the policy no longer errored out but it returns no results until I removed the filters: statement.  Now it works