s3 - has-statement filter bug fix for multiple similar statements (#2111)
* Fix bug when multiple S3 policy stmts are similar

Stop looking for required_statements once it has been found.

This fixes a bug that caused c7n to die when `has-statement` filter was run
on an S3 bucket policy with multiple similar statements.

For example, a bucket policy like:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "StatementOne",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": [
                        "public-read"
                    ]
                }
            }
            "Resource": "arn:aws:s3:::my-bucket/*"
        },
        {
            "Sid": "StatementTwo",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::111122223333:root"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::my-bucket/*"
        }
    ]
}

paired with an policy like:

policies:
  - name: s3-public-bucket-policy
    resource: s3
    filters:
      - type: has-statement
        statements:
          - Effect: Allow
            Action: 's3:PutObject'

caused c7n to fail with an error like:
ValueError: list.remove(x): x not in list

* Add unit test for similar S3 statements

This test fails without the fix to capitalone/cloud-custodian#2111 and
passes with it.

* Use test account number