S3 bucket ACL schema bug
There is a repeated 'READ' but there is no 'FULL_CONTROL' causing exception below:

```
 File "/var/task/c7n/commands.py", line 66, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/var/task/c7n/policy.py", line 72, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy s3
'FULL_CONTROL' is not one of ['READ', 'WRITE', 'WRITE_ACP', 'READ', 'READ_ACP']

Failed validating 'enum' in schema[5]['properties']['permissions']['items']:
    {'enum': ['READ', 'WRITE', 'WRITE_ACP', 'READ', 'READ_ACP'],
     'type': 'string'}

On instance['permissions'][4]:
    'FULL_CONTROL'
```