sg unused - use batches when checking group references (#1024)
When running against an account + region that contains more than 200 security groups
the "unused security group" filter would crash with an AWS ClientError because the
describe_security_group_references() call specified too many groups:

> ClientError: An error occurred (ResourceCountExceeded) when calling the DescribeSecurityGroupReferences operation: The number of resources allowed for this request (200) is exceeded

The fix implemented here is to use `utils.chunks()` to issue a series of smaller requests instead of a single large request.